name: Build rinetd (manual version input)

on:
  workflow_dispatch:
    inputs:
      version:
        description: "输入 rinetd 版本号（例如 'main', 'v0.73', 'v0.72'）"
        required: true
        default: "main"  # 默认值（可选）
        type: string     # 关键修改：允许自由输入文本
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FILE_NAME: "rinetd${{ github.event.inputs.version != 'main' && format('-{0}', github.event.inputs.version) || '' }}"
    steps:
      - name: Checkout rinetd
        uses: actions/checkout@v4
        with:
          repository: samhocevar/rinetd  # 目标仓库
          ref: ${{ github.event.inputs.version }}  # 版本号（main/v0.73等）
          path: rinetd-src  # 指定存放目录
      # 步骤2：安装依赖
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc make automake
      # 步骤3：编译
      - name: Build
        run: |
          cd rinetd-src
          ./bootstrap && ./configure && make && sudo make install
          # 验证安装是否成功
          which rinetd || { echo "编译失败！"; exit 1; }
      # 步骤4：打包二进制
      - name: Prepare release asset
        run: |
          cp rinetd-src/rinetd ./${{ env.FILE_NAME }}
          tar -czvf ${{ env.FILE_NAME }}.tar.gz ${{ env.FILE_NAME }}
          echo "ASSET_PATH=${{ env.FILE_NAME }}.tar.gz" >> $GITHUB_ENV
      # 步骤5：发布到 GitHub Release
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: rinetd ${{ github.event.inputs.version }}
          body: "Automatically built rinetd binary for ${{ github.event.inputs.version }}"
          files: ${{ env.ASSET_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
